### ISSUE TITLE
Noob issue

### ISSUE THREAD

**Issue by lopesdasilva** [UweTrottmann/trakt-java#45]
Hi, Im trying to use your library on android.
But im failing to do so.

I'm calling this on create, because I though with okhttp and retrofit I would need Async task. is it so?

  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        TraktV2 manager = new TraktV2();
        manager.setAccessToken(token);
        manager.movies().trending(1,3, Extended.DEFAULT_MIN);
    }
But i'm getting:

 java.lang.RuntimeException: Unable to start activity ComponentInfo{lopesdasilva.mt_tests.myapplication/lopesdasilva.mt_tests.myapplication.MainActivity}: retrofit.RetrofitError
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
          (...)
     Caused by: retrofit.RetrofitError
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            (...)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
            at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:259)
            at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:233)
            (...)

Thanks for your time and work

**Comment by UweTrottmann** [comment]
If you look at the stack trace and go through the exception stack (look at the `Caused by` lines), you can see the original cause:
`Caused by: android.os.NetworkOnMainThreadException`

If that is not obvious already, just google it (everybody does ;). You would end up e.g. at [this stackoverflow post](http://stackoverflow.com/questions/6343166/android-os-networkonmainthreadexception) (have a look!).

**Comment by UweTrottmann** [comment]
Btw, I also updated the [README](https://github.com/UweTrottmann/trakt-java/blob/master/README.md) for the trakt v2 release.
