### ISSUE TITLE
SocketException when trying to get access token

### ISSUE THREAD

**Issue by mattkranzler5** [UweTrottmann/trakt-java#56]
I'm getting this exception frequently (but not every time) when trying to retrieve an access token after already getting an authorization code. Any ideas?

```java
org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.net.SocketException: Socket is closed
            at com.uwetrottmann.trakt.v2.TraktHttpClient.execute(TraktHttpClient.java:77)
            at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
            at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
            at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:71)
            at com.uwetrottmann.trakt.v2.TraktV2.getAccessToken(TraktV2.java:135)
```

**Comment by mattkranzler5** [comment]
I'm getting the similar exceptions when trying to access the user's settings. 

```java
java.net.SocketException: Socket is closed
            at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:230)
            at com.android.org.conscrypt.OpenSSLSocketImpl.access$000(OpenSSLSocketImpl.java:57)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:725)
            at okio.Okio$1.write(Okio.java:78)
            at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
            at okio.RealBufferedSink.flush(RealBufferedSink.java:185)
            at com.squareup.okhttp.internal.spdy.Spdy3$Writer.synStream(Spdy3.java:339)
            at com.squareup.okhttp.internal.spdy.SpdyConnection.newStream(SpdyConnection.java:266)
            at com.squareup.okhttp.internal.spdy.SpdyConnection.newStream(SpdyConnection.java:242)
            at com.squareup.okhttp.internal.http.SpdyTransport.writeRequestHeaders(SpdyTransport.java:89)
            at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:775)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:645)
            at com.squareup.okhttp.Call.getResponse(Call.java:263)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy1.settings(Unknown Source)
```

**Comment by UweTrottmann** [comment]
Looks like the connection just timed out.

In the `TraktV2.getAccessToken` case, make sure to properly handle `OAuthSystemException` and `OAuthProblemException`.

For the service method calls make sure to use them inside a try-catch-block for `RetrofitException`. See https://github.com/UweTrottmann/trakt-java#calling-methods.

**Comment by mattkranzler5** [comment]
I am handling those exceptions. What's interesting is that even the socket timeout happened pretty much immediately. If I add a retry around each call it will succeed after 1-3 tries. I'd obviously prefer not to have to add a retry workaround, but I can't seem to figure out why it is failing intermittently.

**Comment by UweTrottmann** [comment]
I noticed some possibly related behavior. Though it was related to how trakt's CDN (Cloudflare) was handling secure connections. Sometimes it would downgrade to SSL 3.0 which is not supported any longer by okhttp, breaking the connection.

I'm not sure how this can happen though (AFAIK the client/okhttp should correctly advertise supported encryption protocols).

Sorry I don't have any real pointers here.

**Comment by UweTrottmann** [comment]
Closing this until there is a specific issue that can be fixed in this library.
